---
site_name: Benjamin Bushnell
repo_name: website
# site_dir: public
site_url: https://wwww.benjaminbushnell.com
docs_dir: docs
theme:
  name: material
  custom_dir: overrides
  logo: img/ben_photo.jpeg
  favicon: img/favicon.ico
  icon:
    annotation: material/plus-circle
  features:
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.tabs
    - navigation.footer
  font:
    # https://fonts.google.com/
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search:
      lang: en
  - mermaid2
  - blog
extra:
  social:
    - icon: simple/soundcloud
      link: https://soundcloud.com/voxide
    - icon: simple/spotify
      link: https://open.spotify.com/artist/7D0S25Hwms2iiy65lpAOJW
    - icon: simple/applemusic
      link: https://music.apple.com/us/artist/voxide/920215932
    - icon: fontawesome/solid/book
      link: https://books.benjaminbushnell.com
    - icon: simple/youtube
      link: https://www.youtube.com/@benjaminbushnell
    - icon: simple/github
      link: https://github.com/VoxideNebula
  generator: false
  blog:
    dir: docs/blog
