---
site_name: benjaminbushnell
repo_name: website
repo_url: https://github.com/VoxideNebula/website
# site_dir: docs
site_url: https://benjaminbushnell.com
docs_dir: docs
theme:
  name: material
  logo: img/ben_photo.jpeg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/gitlab
    annotation: material/plus-circle
  features:
    - content.code.copy
    - content.code.select
    - content.action.edit
    - header.autohide
    - navigation.tabs
    - navigation.footer
  font:
    # https://fonts.google.com/
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search:
      lang: en
  - mermaid2
  - blog
extra:
  generator: false
  blog:
    dir: docs/blog
    author: Benjamin Bushnell
    author_image: https://code.chs.usgs.gov/uploads/-/system/user/avatar/1295/avatar.png
